# -*- coding: utf-8 -*-
"""okaivd_lab4_markova_bsb25-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jLBR5SuSg3A3QdickjThssBfYYJY4Bj
"""

Маркова Ульяна Сергеевна
группа БСБ25-01
ОКАИВД. Лабораторная работа №4

import pandas as pd
import numpy as np

# 1.1 Импорт данных
url = 'https://raw.githubusercontent.com/EvgeniiSopovGitHub/datasets_uni/main/okaivd/lab_4_raw_data.csv'
df = pd.read_csv(url, sep=';', index_col='date', decimal='.')

print("Shape:", df.shape)
print("\nInfo:")
print(df.info())
print("\nHead:")
print(df.head())

# 1.2 Заполнение пропусков средними значениями по столбцам
means = df.mean()
df_filled = df.fillna(means)

print("\nПосле заполнения пропусков:")
print(df_filled.info())

# 1.3 Работа с данными
df_filled['min'] = df_filled.min(axis=1)
df_filled['median'] = df_filled.median(axis=1)
df_filled['max'] = df_filled.max(axis=1)

mean_vals = df_filled.iloc[:, :10].mean(axis=1)
std_vals = df_filled.iloc[:, :10].std(axis=1)
df_filled['mean/std'] = mean_vals.round(2).astype(str) + '/' + std_vals.round(2).astype(str)

average_row = df_filled.iloc[:, :10].mean()
average_row['min'] = df_filled.iloc[:, :10].min().min()
average_row['median'] = df_filled.iloc[:, :10].median().median()
average_row['max'] = df_filled.iloc[:, :10].max().max()
average_row['mean/std'] = np.nan

df_final = pd.concat([df_filled, pd.DataFrame([average_row], index=['average_annual'])])

print("\nFinal head:")
print(df_final.head())
print("\nFinal tail:")
print(df_final.tail())

# 1.4 Экспорт
filename = 'lab4_bsb25-01_sopov.csv'
df_final.to_csv(filename, sep=',', decimal='.')

print(f"\nФайл сохранён: {filename}")